name: XSS audit
on: [pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Dalfox scan
        uses: hahwul/action-dalfox@main
        id: xss-result
        with:
          target: 'https://safe-team.dev.gnosisdev.com/app/rin:0xb3b83bf204C458B461de9B0CD2739DB152b4fa5A/apps'
          mode: url
